# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 308)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 261, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.baseScheduleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.baseScheduleLabel.setObjectName("baseScheduleLabel")
        self.horizontalLayout.addWidget(self.baseScheduleLabel)
        self.openBaseScheduleBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openBaseScheduleBtn.setObjectName("openBaseScheduleBtn")
        self.horizontalLayout.addWidget(self.openBaseScheduleBtn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(19, 110, 261, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newScheduleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.newScheduleLabel.setObjectName("newScheduleLabel")
        self.horizontalLayout_2.addWidget(self.newScheduleLabel)
        self.openNewScheduleBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.openNewScheduleBtn.setObjectName("openNewScheduleBtn")
        self.horizontalLayout_2.addWidget(self.openNewScheduleBtn)
        self.findChangesBtn = QtWidgets.QPushButton(self.centralwidget)
        self.findChangesBtn.setGeometry(QtCore.QRect(290, 160, 131, 23))
        self.findChangesBtn.setObjectName("findChangesBtn")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(110, 270, 161, 21))
        self.statusLabel.setObjectName("statusLabel")
        self.baseProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.baseProgressBar.setGeometry(QtCore.QRect(20, 70, 261, 23))
        self.baseProgressBar.setProperty("value", 24)
        self.baseProgressBar.setObjectName("baseProgressBar")
        self.newProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.newProgressBar.setGeometry(QtCore.QRect(20, 160, 261, 23))
        self.newProgressBar.setProperty("value", 24)
        self.newProgressBar.setObjectName("newProgressBar")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(290, 60, 141, 41))
        self.checkBox.setObjectName("checkBox")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 120, 131, 22))
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baseScheduleLabel.setText(_translate("MainWindow", "Выберите базовое расписание"))
        self.openBaseScheduleBtn.setText(_translate("MainWindow", "Открыть"))
        self.newScheduleLabel.setText(_translate("MainWindow", "Выберите расписание с изменениями"))
        self.openNewScheduleBtn.setText(_translate("MainWindow", "Открыть"))
        self.findChangesBtn.setText(_translate("MainWindow", "Отследить изменения"))
        self.statusLabel.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox.setText(_translate("MainWindow", "собрать расписание\n"
"на определенный день"))
